version: '3.8'

services:
  backend:
    build: ./backend
    networks:
      - todo-network

  frontend:
    build: ./frontend
    networks:
      - todo-network

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:
